language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x gradlew
# Travis CI Server's Home

cache:
  - directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hyunwoo892579@gmail.com


before_deploy:
  - zip -r InstagramJpa *
  - mkdir -p deploy
  - mv InstagramJpa.zip deploy/InstagramJpa.zip

deploy:
  - provider: s3
    access_key_id: AKIARWBFNWPQXJH5K5PW
    secret_access_key: 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
    bucket: imenu-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

#Travis 적용