language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x gradlew
# Travis CI Server's Home

cache:
  - directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hyunwoo892579@gmail.com

before_deploy:
  # 1
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  # 2
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  # 3
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/InstagramJpa.zip # deploy로 zip파일 이동


deploy:
  - provider: s3
    access_key_id: AKIARWBFNWPQXJH5K5PW
    secret_access_key: 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
    bucket: imenu-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: AKIARWBFNWPQXJH5K5PW
    secret_access_key: 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
    bucket: imenu-build # S3 버킷
    key: InstagramJpa.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: imenu-code-deploy # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: imenu-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
